# Generated by Django 4.2.4 on 2023-09-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('goal', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('periode', models.CharField(max_length=50)),
                ('hit', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('goal_type', models.CharField(choices=[('1', 'Receita'), ('2', 'Abatimento de dívida'), ('3', 'Economia de gastos')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='GoalsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
    ]
